### ISSUE TITLE
Feature Request: CLI

### ISSUE THREAD

**Issue by flynow10** [hamidsamak/pheditor#12]
This may be to far from the original idea but it would be nice to have a command line at the bottom. Something like in putty or vs code terminal

**Comment by hamidsamak** [comment]
It is possible, but totally depends on your server configuration. The shell execution functions are disabled on most shared servers because of security reasons.
Also the web server user permission (like httpd, apache and nginx users on Linux) have limited access to shell commands and depends on server definitions.
But I like the idea and try to keep it up on the list.

**Comment by hamidsamak** [comment]
Terminal feature came true. Please clone the latest version.
